[package]
name = "xtask"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = {workspace = true}
lazy_static = {workspace = true}
xshell = {workspace = true}
xflags = {workspace = true}
which = {workspace = true}
toml = {workspace = true}
prost-build = {workspace = true}
