[package]
name = "fixture-plugin-for-tests"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2021"
license = "MIT"

[dependencies]
serde = {workspace = true}
serde_json = {workspace = true}
zellij-tile = { path = "../../zellij-tile" }
