[package]
name = "zellij-utils"
version = "0.40.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2021"
description = "A utility library for Zellij client and server"
license = "MIT"
include = ["src/**/*", "assets/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
backtrace = { workspace = true }
rmp-serde = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
clap_complete = { workspace = true }
colored = { workspace = true }
colorsys = { workspace = true }
crossbeam = { workspace = true }
directories = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
once_cell = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strip-ansi-escapes = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
vte = { workspace = true }
log = { workspace = true }
unicode-width = { workspace = true }
miette = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
kdl = { workspace = true }
shellexpand = { workspace = true }
uuid = { workspace = true }
async-channel = { workspace = true }
include_dir = { workspace = true }
prost = { workspace = true }
common-path = { workspace = true }

#[cfg(not(target_family = "wasm"))]
[target.'cfg(not(target_family = "wasm"))'.dependencies]
termwiz = "0.20.0"
log4rs = "1.2.0"
signal-hook = "0.3"
interprocess = "1.2.1"
async-std = { version = "1.3.0", features = ["unstable", "attributes"] }
notify-debouncer-full = "0.1.0"
humantime = "2.1.0"
futures = "0.3.28"
surf = { version = "2.3.2", default-features = false, features = [
    "curl-client",
] }
openssl-sys = { version = "0.9.93", features = ["vendored"] }

[dev-dependencies]
insta = { version = "1.6.0", features = ["backtrace"] }
expect-test = "1.4.1"

[build-dependencies]
prost-build = "0.11.9"

[features]
# If this feature is NOT set (default):
#   - builtin plugins (status-bar, tab-bar, ...) are loaded directly from the application binary
# If this feature is set:
#   - builtin plugins MUST be available from whatever is configured as `PLUGIN_DIR`
disable_automatic_asset_installation = []
unstable = []
plugins_from_target = []
