[package]
name = "zellij-server"
version = "0.40.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2021"
description = "The server-side library for Zellij"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
highway = { workspace = true }
ansi_term = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
byteorder = { workspace = true }
daemonize = { workspace = true }
serde_json = { workspace = true }
unicode-width = { workspace = true }
url = { workspace = true }
wasmer = { workspace = true }
wasmer-wasi = { workspace = true }
cassowary = { workspace = true }
zellij-utils = { path = "../zellij-utils/", version = "0.40.0" }
log = { workspace = true }
typetag = { workspace = true }
chrono = { workspace = true }
close_fds = { workspace = true }
sysinfo = { workspace = true }
sixel-tokenizer = { workspace = true }
sixel-image = { workspace = true }
arrayvec = { workspace = true }
uuid = { workspace = true }
semver = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
wasmer = {  workspace = true , features = ["singlepass"] }

[features]
singlepass = ["wasmer/singlepass"]
