[package]
name = "zellij-client"
version = "0.40.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2021"
description = "The client-side library for Zellij"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { workspace = true }
serde = { workspace = true }
url = { workspace = true , features = ["serde"] }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
zellij-utils = { path = "../zellij-utils/", version = "0.40.0" }
log = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[features]
unstable = [ ]
